# Generated by Django 3.2.3 on 2021-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('avg_rainfall', models.FloatField()),
                ('catchmentArea', models.FloatField()),
                ('population', models.IntegerField()),
                ('losses', models.FloatField()),
                ('yeild', models.FloatField()),
                ('yeild_after_losses', models.FloatField()),
                ('demand', models.FloatField()),
                ('capacity_of_lake', models.FloatField()),
                ('deficit', models.CharField(max_length=50)),
            ],
        ),
    ]
